
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;


public class CarXInfo extends javax.swing.JFrame {

    String carBrand,carModel,carYear;
    public CarXInfo() {
        
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BrandCombo = new javax.swing.JComboBox<>();
        ModelCombo = new javax.swing.JComboBox<>();
        YearCombo = new javax.swing.JComboBox<>();
        YearLabel = new javax.swing.JLabel();
        BrandLabel = new javax.swing.JLabel();
        ModelLabel = new javax.swing.JLabel();
        Ok = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        BackGroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(30, 30, 0, 0));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(557, 435));
        setMinimumSize(new java.awt.Dimension(557, 435));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(557, 435));
        setResizable(false);
        getContentPane().setLayout(null);

        BrandCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        BrandCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Toyota", "Suzuki", "Daihatsu" }));
        BrandCombo.setToolTipText("Year");
        BrandCombo.setBorder(null);
        BrandCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BrandCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandComboActionPerformed(evt);
            }
        });
        getContentPane().add(BrandCombo);
        BrandCombo.setBounds(340, 110, 100, 30);

        ModelCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ModelCombo.setAutoscrolls(true);
        ModelCombo.setBorder(null);
        ModelCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModelCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelComboActionPerformed(evt);
            }
        });
        getContentPane().add(ModelCombo);
        ModelCombo.setBounds(340, 190, 100, 30);

        YearCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2013", "2014", "2015", "2016" }));
        YearCombo.setBorder(null);
        YearCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        YearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearComboActionPerformed(evt);
            }
        });
        getContentPane().add(YearCombo);
        YearCombo.setBounds(340, 268, 100, 30);

        YearLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(YearLabel);
        YearLabel.setBounds(190, 268, 100, 30);

        BrandLabel.setBackground(new java.awt.Color(153, 153, 153));
        BrandLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(BrandLabel);
        BrandLabel.setBounds(190, 110, 100, 30);

        ModelLabel.setBackground(new java.awt.Color(102, 102, 102));
        ModelLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(ModelLabel);
        ModelLabel.setBounds(190, 190, 100, 30);

        Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkMouseClicked(evt);
            }
        });
        getContentPane().add(Ok);
        Ok.setBounds(427, 388, 80, 25);

        Exit.setFocusCycleRoot(true);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(56, 385, 80, 30);

        BackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mustang.png"))); // NOI18N
        BackGroundImage.setAlignmentY(0.0F);
        getContentPane().add(BackGroundImage);
        BackGroundImage.setBounds(0, 0, 557, 435);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrandComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandComboActionPerformed
        BrandLabel.setText(BrandCombo.getSelectedItem().toString());
        this.carBrand=BrandLabel.getText();
        switch(carBrand){
            case "Honda":{
            ModelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Accord","Civic","City","Vezel","Fit"}));
            break;
            }
            case "Toyota": {
            ModelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Corolla","Vitz","Prius","Passo","Prado"}));
            break;
            }
            case "Suzuki":{
            ModelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Alto","Mehran","Cultus","Swift","Liana"}));
            break;
            }
            case "Daihatsu":{
            ModelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Cuore","Charade","Move","Mira","Boon"}));
            break;
            }
        }
    }//GEN-LAST:event_BrandComboActionPerformed

    private void YearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearComboActionPerformed
        this.carYear=YearCombo.getSelectedItem().toString();
        YearLabel.setText(carYear);
        YearCombo.getSelectedItem().toString();
        
    }//GEN-LAST:event_YearComboActionPerformed

    private void OkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkMouseClicked
        if(carBrand!=null&&carModel!=null&carYear!=null){
        Pics obj=new Pics(carBrand,carModel,carYear);
        obj.setVisible(true);
        obj.setBackground(new Color(0,0,0,0));
        carBrand=null;carModel=null;carYear=null;
        BrandLabel.setText("");ModelLabel.setText("");YearLabel.setText("");
        }
        else{
        JOptionPane.showMessageDialog(null, "Please select the required Info");
    }
    }//GEN-LAST:event_OkMouseClicked

    private void ModelComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelComboActionPerformed
        this.carModel=ModelCombo.getSelectedItem().toString();
        ModelLabel.setText(carModel);
        
        switch (carModel) {
            case "Charade":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"1984","1986","1987","1988"} ));
                break;
            case "Cuore":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2004","2006","2007","2008"} ));
                break;
            case "Move":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2011","2012","2013","2014"} ));
                break;
            case "Mira":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2009","2012","2013","2014"} ));
                break;
            case "Boon":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2006","2007","2013","2014"} ));
                break;
            case "Accord":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2002","2004","2005","2007"} ));
                break;
            case "Civic":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2005","2011","2015","2016"} ));
                break;
            case "Corolla":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2007","2011","2014","2016"} ));
                break;
            case "Prado":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2005","2008","2011","2013"} ));
                break;
            case "Passo":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2007","2010","2012","2015"} ));
                break;
            case "Prius":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2007","2010","2011","2013"} ));
                break;
            case "Cultus":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2008","2011","2013","2015"} ));
                break;
            case "Liana":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2006","2007","2008","2010"} ));
                break;
            case "Mehran":
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2011","2012","2014","2015"} ));
                break;
            default:
                YearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2013","2014","2015","2016"} ));
                break;
        }
        
    }//GEN-LAST:event_ModelComboActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
      WindowEvent close=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(close);
    }//GEN-LAST:event_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarXInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarXInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarXInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarXInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarXInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundImage;
    private javax.swing.JComboBox<String> BrandCombo;
    private javax.swing.JLabel BrandLabel;
    private javax.swing.JLabel Exit;
    private javax.swing.JComboBox<String> ModelCombo;
    private javax.swing.JLabel ModelLabel;
    private javax.swing.JLabel Ok;
    private javax.swing.JComboBox<String> YearCombo;
    private javax.swing.JLabel YearLabel;
    // End of variables declaration//GEN-END:variables

    private void setOpacity(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
